name: SBOM
on:
  push:
jobs:
  sbom-assests:
    name: Release sbom
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate sbom for karmada file system
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'fs'
          format: 'spdx'
          output: 'sbom-karmada.spdx'
          scan-ref: "/github/workspace/"
      - name: Display the sbom
        run: |
          cat sbom-karmada.spdx
