name: SBOM
on:
  push:
jobs:
  sbom-assests:
    name: Release sbom
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Generate sbom for karmada file system
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'fs'
          format: 'spdx'
          output: '/tmp/trivy-sbom.spdx'
          scan-ref: "/github/workspace/"
      - name: Tar the sbom files
        run: |
          cat /tmp/trivy-sbom.spdx
          cd /tmp && tar -zcf sbom.tar.gz *.spdx
          ll |grep sbom.tar.gz
