name: SBOM
on:
  push:
jobs:
  sbom:
    name: sbom
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: generator sbom
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'fs'
          format: 'spdx'
          output: 'trivy-sbom.spdx'
      - name: display
        run: |
          cat trivy-sbom.spdx
