name: SBOM
on:
  push:
jobs:
  sbom-assests:
    name: Release sbom
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate sbom for karmada file system
        uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: 'fs'
          format: 'spdx'
          output: 'sbom-karmada.spdx'
          scan-ref: "${{ github.workspace }}/"
      - name: Tar the sbom files
        run: |
          cat sbom-karmada.spdx
          tar -zcf sbom.tar.gz *.spdx
